version: '3.8'

services:
  # react
  client:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - HOST_UID=${HOST_UID}
        - HOST_GID=${HOST_GID}
    ports:
      - "4200:4200"
    volumes:
      - ./:/app
    
  # npm
  npm:
    image: node:lts-alpine3.17
    working_dir: /app
    entrypoint: npm
    user: ${HOST_UID}:${HOST_GID}
    tty: true
    volumes:
      - ./:/app


